Repository stackabletech/spark-operator, pull requests merged in 2021-04, with the labels that each got.

#51 Respect Apache Trademark rules
  README.adoc
Labels: type: documentation

#48 Restart command implementation using operator-rs command_controller
  Cargo.lock
  common/Cargo.toml
  crd/Cargo.toml
  crd/restart.command.crd.yaml
  crd/sparkcluster.crd.yaml
  crd/src/commands.rs
  crd/src/lib.rs
  crd/start.command.crd.yaml
  crd/stop.command.crd.yaml
  examples/restart.command.example.yaml
  examples/start.command.example.yaml
  examples/stop.command.example.yaml
  operator/Cargo.toml
  operator/src/command_utils.rs
  operator/src/error.rs
  operator/src/lib.rs
  server/src/main.rs
Labels: type/enhancement

#65 Remove curl debug logging
  .github/workflows/nightly.yml
  Cargo.lock
  operator/Cargo.toml
Labels: priority/critical, size/XS, type/bug
