Repository stackabletech/spark-operator, pull requests merged in 2021-08, with the labels that each got.

#101 Integrate operator rs changes with product config
  .github/workflows/rust.yml
  .gitignore
  Cargo.lock
  README.adoc
  crd/Cargo.toml
  crd/src/bin/generate_crds.rs
  crd/src/commands.rs
  crd/src/error.rs
  crd/src/lib.rs
  deploy/config-spec/properties.yaml
  deploy/crd/restart.command.crd.yaml
  deploy/crd/sparkcluster.crd.yaml
  deploy/crd/start.command.crd.yaml
  deploy/crd/stop.command.crd.yaml
  docs/modules/ROOT/pages/usage.adoc
  examples/restart.command.example.yaml
  examples/sparkcluster.example.v3.0.1.yaml
  examples/start.command.example.yaml
  examples/stop.command.example.yaml
  operator/Cargo.toml
  operator/src/command_utils.rs
  operator/src/config.rs
  operator/src/error.rs
  operator/src/lib.rs
  operator/src/pod_utils.rs
  server/src/bin/generate_crds.rs
  server/src/main.rs
  test_utils/Cargo.toml
  test_utils/data/test_spark_cluster.yaml
  test_utils/src/cluster.rs
  test_utils/src/lib.rs
Labels: type/enhancement, priority/medium

#115 Feature/enable monitoring
  Cargo.lock
  common/src/constants.rs
  crd/src/lib.rs
  deploy/config-spec/properties.yaml
  deploy/crd/sparkcluster.crd.yaml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/commandline_args.adoc
  docs/modules/ROOT/pages/configuration.adoc
  docs/modules/ROOT/pages/usage.adoc
  examples/sparkcluster.example.v3.0.1.yaml
  operator/src/config.rs
  operator/src/error.rs
  operator/src/lib.rs
  operator/src/pod_utils.rs
  server/Cargo.toml
  server/packaging/buildrpm.sh
  server/packaging/copy_assets.py
  server/packaging/rpm/SOURCES/stackable-spark-operator-server-VERSION/usr/lib/systemd/system/stackable-spark-operator-server.service
  server/packaging/rpm/SPECS/stackable-spark-operator-server.spec
  server/src/main.rs
  test_utils/src/lib.rs
Labels: type/enhancement, priority/medium

#118 Print startup diagnostic information using the built crate
  Cargo.lock
  server/Cargo.toml
  server/build.rs
  server/src/main.rs
Labels: type/enhancement, priority/medium

#117 Adds CLI handling
  Cargo.lock
  crd/Cargo.toml
  crd/src/bin/generate_crds.rs
  operator/Cargo.toml
  operator/src/lib.rs
  server/Cargo.toml
  server/build.rs
  server/src/main.rs
  test_utils/Cargo.toml
Labels: type/enhancement, priority/high

#125 Only print diagnostic output _after_ CLI has been handled & cargo update
  Cargo.lock
  server/src/main.rs
Labels: type/bug, priority/medium

#126 Adapted to operator-rs build_resource_name and create_config_map.
  Cargo.lock
  operator/src/error.rs
  operator/src/lib.rs
Labels: type/enhancement, priority/high
