Repository stackabletech/spark-operator, pull requests merged in 2021-06, with the labels that each got.

#94 Update semver to 1.0
  Cargo.lock
  crd/Cargo.toml
  crd/src/lib.rs
  operator/Cargo.toml
  operator/src/error.rs
Labels: priority/low, type/dependencies

#95 Adapt to operator kube-rs 0.56 and status traits
  Cargo.lock
  crd/Cargo.toml
  crd/src/lib.rs
  operator/Cargo.toml
  operator/src/command_utils.rs
  operator/src/lib.rs
  operator/src/pod_utils.rs
  test_utils/Cargo.toml
Labels: priority/high, type/enhancement

#97 Fix clippy warnings introduced in Rust 1.53
  crd/src/lib.rs
Labels: priority/critical, type/enhancement

#98 Add Docker support
  .dockerignore
  .github/workflows/docker.yml
  Makefile
  docker/Dockerfile
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/installation.adoc
Labels: priority/high, type/enhancement
