Repository stackabletech/spark-operator, pull requests merged in 2021-09, with the labels that each got.

#131 Project updates
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/rust.yml
  CHANGELOG.md
  Cargo.lock
  crd/Cargo.toml
  deny.toml
  operator/Cargo.toml
  server/Cargo.toml
  test_utils/Cargo.toml
Labels: type/enhancement, priority/low

#135 Updated dependencies
  Cargo.lock
Labels: type/dependencies

#152 Implemented versioning for up and downgrades from operator-rs
  CHANGELOG.md
  Cargo.lock
  deploy/crd/sparkcluster.crd.yaml
  rust/crd/Cargo.toml
  rust/crd/src/lib.rs
  rust/operator-binary/Cargo.toml
  rust/operator/Cargo.toml
  rust/operator/src/lib.rs
  rust/test_utils/Cargo.toml
Labels: type/enhancement, priority/high
