Repository stackabletech/spark-operator, pull requests merged in 2021-05, with the labels that each got.

#70 Added clean command to rust build.
  .github/workflows/rust.yml
Labels: type/enhancement

#78 Add Antora documentation
  README.adoc
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/building.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/usage.adoc
Labels: priority/low, size/S, type/documentation

#64 Refactor for operator-rs and kube 0.52
  Cargo.lock
  README.adoc
  common/src/constants.rs
  crd/Cargo.toml
  crd/restart.command.crd.yaml
  crd/sparkcluster.crd.yaml
  crd/src/lib.rs
  crd/start.command.crd.yaml
  crd/stop.command.crd.yaml
  examples/restart.command.example.yaml
  examples/sparkcluster.example.v3.0.1.yaml
  examples/start.command.example.yaml
  examples/stop.command.example.yaml
  operator/Cargo.toml
  operator/src/command_utils.rs
  operator/src/config.rs
  operator/src/error.rs
  operator/src/lib.rs
  operator/src/pod_utils.rs
  server/Cargo.toml
  server/src/bin/generate_crds.rs
  server/src/main.rs
  test_utils/Cargo.toml
  test_utils/data/test_spark_cluster.yaml
  test_utils/src/cluster.rs
  test_utils/src/lib.rs
Labels: hackathon, priority/medium, size/XL, type/enhancement

#82 Fix condition
  operator/src/lib.rs
Labels: priority/high, size/XS, type/bug

#87 Bring project up to current Stackable best practices
  .github/dependabot.yml
  .github/workflows/build_artifacts.yml
  .github/workflows/rust.yml
  Cargo.lock
  common/Cargo.toml
  crd/Cargo.toml
  crd/src/commands.rs
  crd/src/lib.rs
  deploy/crd/restart.command.crd.yaml
  deploy/crd/sparkcluster.crd.yaml
  deploy/crd/start.command.crd.yaml
  deploy/crd/stop.command.crd.yaml
  docs/modules/ROOT/pages/building.adoc
  operator/Cargo.toml
  operator/src/config.rs
  operator/src/pod_utils.rs
  server/Cargo.toml
  server/packaging/rpm/SPECS/stackable-spark-operator-server.spec
  server/src/main.rs
Labels: priority/low, type/enhancement
